# Generated by Django 4.1.7 on 2023-03-18 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_is_staff_usermodel_is_stuff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermodel",
            old_name="is_stuff",
            new_name="is_staff",
        ),
    ]
