version: '3'

services:
  postgres:
    container_name: django-postgres
    image: postgres:13-alpine3.17
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: django_todos
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432